### ISSUE TITLE
Needs updating for incomming ntfs3

### ISSUE THREAD

**Issue by fennectech** [davidwed/ultradefrag#1]
with NTFS3 becomming defacto standard very soon this tool will need to be updated to not rely on NTFS-3g
```
[fennectech@Jasper /run/media/fennectech/5B1670D9159C166C]$  udefrag /dev/sdc1
udefrag: error while loading shared libraries: libntfs-3g.so.88: cannot open shared object file: No such file or directory


```

**Comment by chromer030** [comment]
Is this repo of udefrag ?
Latest udefrag version (5.0.0AB.8) was from http://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html

**Comment by chromer030** [comment]
@fennectech 
Take a look at this repo : https://github.com/749/UltraDefrag4Linux
